const product=document.querySelector("#product"),materialProduct=document.querySelector("#materialProduct"),progress=document.querySelector("#progress"),header=document.querySelector("#header");
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function particles(){const box=document.querySelector("#particles");for(let i=0;i<95;i++){let p=document.createElement("i");p.className="particle";p.style.left=Math.random()*100+"%";p.style.animationDuration=(5+Math.random()*10)+"s";p.style.animationDelay=(-Math.random()*12)+"s";p.style.setProperty("--drift",(Math.random()*180-90)+"px");p.style.opacity=Math.random()*.7;let s=Math.random()*3+.8;p.style.width=s+"px";p.style.height=s+"px";box.appendChild(p)}}
function scrollFX(){let y=scrollY,max=document.body.scrollHeight-innerHeight,p=clamp(y/max,0,1);progress.style.width=p*100+"%";header.classList.toggle("scrolled",y>40);
let r1=document.querySelector("#design").offsetTop,r2=document.querySelector("#material").offsetTop,r3=document.querySelector("#details").offsetTop;
if(y<r1){let q=clamp(y/r1,0,1);product.style.transform=`translate3d(${q*35}px,${q*70}px,0) rotateX(${-4+q*18}deg) rotateY(${-24+q*150}deg) rotateZ(${q*7}deg) scale(${1-q*.12})`;product.style.filter=`drop-shadow(0 ${60+q*80}px ${45+q*25}px #000c)`;document.querySelector(".hero-copy").style.transform=`translateY(${q*-35}px)`} 
else if(y<r2){let q=clamp((y-r1)/(r2-r1),0,1);product.style.transform=`translate3d(${35-q*250}px,${70-q*20}px,0) rotateX(${14-q*20}deg) rotateY(${126+q*220}deg) rotateZ(${7-q*14}deg) scale(${.88+q*.08})`}
else if(y<r3){let q=clamp((y-r2)/(r3-r2),0,1);materialProduct.style.transform=`translateY(${Math.sin(q*Math.PI)*-35}px) rotateY(${q*300}deg) rotateX(${q*12}deg) scale(${.85+q*.2})`}
}
let last=0;addEventListener("scroll",()=>{requestAnimationFrame(()=>{scrollFX();last=scrollY})},{passive:true});
function reveal(){let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("show");io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>io.observe(x))}
function mouse(){if(!matchMedia("(pointer:fine)").matches)return;addEventListener("mousemove",e=>{let x=e.clientX/innerWidth-.5,y=e.clientY/innerHeight-.5;if(scrollY<innerHeight*.9)product.style.setProperty("filter",`drop-shadow(${x*20}px ${60-y*20}px 45px #000c)`);document.querySelectorAll(".ring").forEach((r,i)=>r.style.marginLeft=x*(i+1)*15+"px")})}
addEventListener("load",()=>{setTimeout(()=>document.querySelector("#loader").classList.add("hide"),1450);particles();reveal();scrollFX();mouse()});
document.querySelectorAll("nav a").forEach(a=>a.addEventListener("click",()=>document.querySelectorAll("nav a").forEach(x=>x.classList.remove("active"))));
const sections=[...document.querySelectorAll("section")];addEventListener("scroll",()=>{let y=scrollY+innerHeight*.45;sections.forEach((s,i)=>{if(y>=s.offsetTop&&y<s.offsetTop+s.offsetHeight)document.querySelectorAll("nav a").forEach((a,j)=>a.classList.toggle("active",i===j))})},{passive:true});
